"""Added new column

Revision ID: 05867b3d4dd5
Revises: 06f808430f2d
Create Date: 2025-12-30 07:45:31.015772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05867b3d4dd5'
down_revision: Union[str, Sequence[str], None] = '06f808430f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('purchase_items', sa.Column('selling_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'selling_price')
    op.drop_column('medicine_batches', 'selling_price')
    # ### end Alembic commands ###
