"""Added new column

Revision ID: 06f808430f2d
Revises: 77d969ab7b62
Create Date: 2025-12-30 07:27:28.747861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f808430f2d'
down_revision: Union[str, Sequence[str], None] = '77d969ab7b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'expiry_date')
    # ### end Alembic commands ###
