"""Added new column

Revision ID: 12feea0ac4e5
Revises: 58a68eb752df
Create Date: 2025-12-30 11:16:02.515364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12feea0ac4e5'
down_revision: Union[str, Sequence[str], None] = '58a68eb752df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('discount_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'discount_type')
    op.drop_column('sale_items', 'discount_amount')
    # ### end Alembic commands ###
