"""drop column

Revision ID: 18662e2907f7
Revises: 12feea0ac4e5
Create Date: 2025-12-30 13:00:00.898878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18662e2907f7'
down_revision: Union[str, Sequence[str], None] = '12feea0ac4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE medicines DROP CONSTRAINT IF EXISTS _name_strength_mfg_uc")
    op.create_unique_constraint('_name_strength_mfg_uc', 'medicines', ['name', 'strength', 'manufacturer', 'medicine_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_strength_mfg_uc', 'medicines', type_='unique')
    op.create_unique_constraint(op.f('_name_strength_mfg_uc'), 'medicines', ['name', 'strength', 'manufacturer', 'medicine_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
