"""remove column

Revision ID: 2a84e501112d
Revises: f996eb310823
Create Date: 2025-12-19 11:08:46.266895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a84e501112d'
down_revision: Union[str, Sequence[str], None] = 'f996eb310823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'manufacturer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
