"""Added new column

Revision ID: 4454d3b45831
Revises: d28f26ac7b8d
Create Date: 2025-12-23 09:20:06.483907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4454d3b45831'
down_revision: Union[str, Sequence[str], None] = 'd28f26ac7b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('medicine_batches', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_medicine_batches_purchase_base_number'), table_name='medicine_batches')
    op.create_index(op.f('ix_medicine_batches_invoice_number'), 'medicine_batches', ['invoice_number'], unique=True)
    op.drop_column('medicine_batches', 'purchase_base_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('purchase_base_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_medicine_batches_invoice_number'), table_name='medicine_batches')
    op.create_index(op.f('ix_medicine_batches_purchase_base_number'), 'medicine_batches', ['purchase_base_number'], unique=True)
    op.drop_column('medicine_batches', 'purchase_date')
    op.drop_column('medicine_batches', 'invoice_number')
    # ### end Alembic commands ###
