"""Added new column

Revision ID: 58a68eb752df
Revises: eb879fd2e1b1
Create Date: 2025-12-30 11:02:47.146409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a68eb752df'
down_revision: Union[str, Sequence[str], None] = 'eb879fd2e1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('discount_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount_type')
    op.drop_column('sales', 'discount_amount')
    # ### end Alembic commands ###
