"""Added new table

Revision ID: 7bcae6bae306
Revises: 60226a3406d5
Create Date: 2025-12-24 10:51:27.868975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcae6bae306'
down_revision: Union[str, Sequence[str], None] = '60226a3406d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('shareholder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'investments', 'shareholders', ['shareholder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investments', type_='foreignkey')
    op.drop_column('investments', 'shareholder_id')
    # ### end Alembic commands ###
