"""change column

Revision ID: 9fe77adbc2f7
Revises: eabf5d08ff63
Create Date: 2025-12-29 15:27:05.719661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe77adbc2f7'
down_revision: Union[str, Sequence[str], None] = 'eabf5d08ff63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('discount_type', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('generic_name', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('strength', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('medicine_type', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('mrp', sa.Float(), nullable=True))
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_manufacturer'), 'medicines', ['manufacturer'], unique=False)
    op.add_column('purchases', sa.Column('discount_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'discount_type')
    op.drop_index(op.f('ix_medicines_manufacturer'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_column('medicines', 'mrp')
    op.drop_column('medicines', 'medicine_type')
    op.drop_column('medicines', 'strength')
    op.drop_column('medicines', 'manufacturer')
    op.drop_column('medicines', 'generic_name')
    op.drop_column('medicine_batches', 'discount_type')
    # ### end Alembic commands ###
