"""add and modify table

Revision ID: a57920798ed2
Revises: 2a84e501112d
Create Date: 2025-12-19 11:49:36.361725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57920798ed2'
down_revision: Union[str, Sequence[str], None] = '2a84e501112d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('buyer_mobile', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('buyer_address', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('due_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'due_amount')
    op.drop_column('sales', 'amount_paid')
    op.drop_column('sales', 'buyer_address')
    op.drop_column('sales', 'buyer_mobile')
    op.drop_column('sales', 'buyer_name')
    # ### end Alembic commands ###
