"""Added account table

Revision ID: a96864d6454d
Revises: 904098dbff9c
Create Date: 2025-12-23 13:22:09.495708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96864d6454d'
down_revision: Union[str, Sequence[str], None] = '904098dbff9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('purchases', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'payment_status')
    op.drop_column('purchases', 'paid_amount')
    # ### end Alembic commands ###
