"""Added new column

Revision ID: c8e1b02f7174
Revises: 89c2d25dc0ee
Create Date: 2025-12-17 14:25:29.221002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e1b02f7174'
down_revision: Union[str, Sequence[str], None] = '89c2d25dc0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medicine_batches', 'units', ['unit_id'], ['id'])
    op.drop_column('medicine_batches', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medicine_batches', type_='foreignkey')
    op.drop_column('medicine_batches', 'unit_id')
    # ### end Alembic commands ###
