"""Added table

Revision ID: d766a3c88192
Revises: 4eacb09e9c2c
Create Date: 2025-12-24 07:15:33.784600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd766a3c88192'
down_revision: Union[str, Sequence[str], None] = '4eacb09e9c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('overtime_rate', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    op.drop_column('employees', 'overtime_rate')
    # ### end Alembic commands ###
