"""add new table

Revision ID: eabf5d08ff63
Revises: 7bcae6bae306
Create Date: 2025-12-24 14:02:26.592634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabf5d08ff63'
down_revision: Union[str, Sequence[str], None] = '7bcae6bae306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shareholders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shareholders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shareholders', type_='foreignkey')
    op.drop_column('shareholders', 'user_id')
    # ### end Alembic commands ###
